#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use CTExport\ExportApplication;
use Symfony\Component\Console\Application;

$application = ExportApplication::create();
$application->run();