#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

// PHP-ini options
ini_set('phar.readonly', 0);

use CTExport\ChurchToolsCliApplication;

$application = ChurchToolsCliApplication::create();
$application->run();