#!/usr/bin/env php
<?php
// application.php

require __DIR__ . '/vendor/autoload.php';

use CTExport\ChurchToolsCliApplication;

$application = ChurchToolsCliApplication::create();
$application->run();