#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use CTExport\ChurchToolsCliApplication;
use Symfony\Component\Console\Application;

$application = ChurchToolsCliApplication::create();
$application->run();